# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171121_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_number',
            new_name='Number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_pw',
        ),
        migrations.AddField(
            model_name='users',
            name='Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='Password',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='Password_Repeat',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
