# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171121_2026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
