# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Orders',
            fields=[
                ('Order_No', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
