# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20171120_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='pro_id',
            field=models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False),
        ),
    ]
