# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20171121_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='pro_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
