# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitems_pro_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField(max_length=100)),
                ('card_holder_name', models.CharField(max_length=30)),
                ('card_num', models.CharField(max_length=19)),
                ('card_expiry', models.CharField(max_length=5)),
                ('card_cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
