# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('product_image', models.TextField(max_length=100)),
                ('product_name', models.CharField(max_length=20)),
                ('product_desc', models.TextField(max_length=100)),
                ('product_category', models.TextField(default='null')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
