# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('cat_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product_details',
            name='cat_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Product_Categories'),
            preserve_default=False,
        ),
    ]
