# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171113_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='product_category',
        ),
    ]
