# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171114_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product_Categories'),
        ),
    ]
